[build]
  functions = "netlify/functions"
  publish = "dist"

  [functions]
  directory = "netlify/functions"

  [[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

  
[dev]
  command = "vite"
  targetPort = 5173
  framework = "vite"
  autoLaunch = true